In [8]:
print("Projet M2 Data Engineering")
print("Exploration, nettoyage et préparation des données")

Projet M2 Data Engineering
Exploration, nettoyage et préparation des données

In [9]:
import os


folders = [
    "data/raw",
    "data/processed",
    "notebooks"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Structure du projet créée avec succès.")

Structure du projet créée avec succès.

In [10]:
!find . -maxdepth 3 -type d

FIND : format incorrect de paramètre

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings

warnings.filterwarnings("ignore")

print("Bibliothèques chargées avec succès.")

Bibliothèques chargées avec succès.

In [12]:
!ls -lh data/raw/

'ls' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

In [13]:
customers = pd.read_csv("../data/raw/customers_data.csv")
products = pd.read_csv("../data/raw/products_data.csv")
sales = pd.read_csv("../data/raw/sales_data.csv")
marketing = pd.read_csv("../data/raw/marketing_data.csv")

In [14]:
print("on va comprendre les donnees après importations.")

print("CUSTOMERS")
print(customers.shape)

print("\nPRODUCTS")
print(products.shape)

print("\nSALES")
print(sales.shape)

print("\nMARKETING")
print(marketing.shape)

on va comprendre les donnees après importations.
CUSTOMERS
(7000, 7)

PRODUCTS
(200, 5)

SALES
(30000, 7)

MARKETING
(100, 8)

In [15]:
display(customers.head())

,Customer_ID,Name,Age,Gender,Location,Join_Date,Total_Spent
0,2001,Customer_2001,33,Female,New York,13 12 2021,0.00
1,2002,Customer_2002,59,Male,New York,08 03 2023,1103.79
2,2003,Customer_2003,51,Male,Houston,29 04 2021,1172.71
3,2004,Customer_2004,18,Male,Houston,04 06 2022,43.91
4,2005,Customer_2005,39,Female,Los Angeles,03 01 2023,1264.34

In [16]:
display(products.head())

   Product_ID Product_Name                Category   Price    Brand
0         101  Product_101  Electronic Accessories   25.72  Brand A
1         102  Product_102  Electronic Accessories  155.32  Brand B
2         103  Product_103               Lifestyle   74.44  Brand C
3         104  Product_104  Electronic Accessories   44.43  Brand D
4         105  Product_105  Electronic Accessories   41.69  Brand E

In [17]:
display(sales.head())

,Sale_ID,Product_ID,Customer_ID,Date,Quantity,Sale_Price,Channel
0,1,204,5647,30 01 2024,2,172.62,Online
1,2,150,6294,12 04 2024,1,58.93,Online
2,3,229,8549,16 01 2024,3,21.12,In-Store
3,4,162,7331,10 02 2024,4,37.58,Online
4,5,104,2926,11 09 2024,1,37.95,Online

In [18]:
display(marketing.head())

,Campaign_ID,Channel,Start_Date,End_Date,Budget,Impressions,Clicks,Conversions
0,1,Email,15 08 2024,07 09 2024,408.47,25803,1103,58
1,2,In-Store,09 10 2024,19 10 2024,3853.39,56256,968,66
2,3,Email,24 04 2024,22 05 2024,915.32,88785,4550,297
3,4,Email,17 10 2024,29 10 2024,2039.20,61076,3548,281
4,5,Online,04 05 2024,25 05 2024,2882.14,138243,10593,1365

In [19]:
print(" Info sur les 4 datasets :")

datasets = {
    "CUSTOMERS": customers,
    "PRODUCTS": products,
    "SALES": sales,
    "MARKETING": marketing
}

for nom, df in datasets.items():
    print("\n" + "=" * 60)
    print(nom)
    print("=" * 60)

    print("Nombre de lignes :", df.shape[0])
    print("Nombre de colonnes :", df.shape[1])

    print("\nColonnes :")
    print(df.columns.tolist())

    print("\nTypes de données :")
    print(df.dtypes)

 Info sur les 4 datasets :

============================================================
CUSTOMERS
============================================================
Nombre de lignes : 7000
Nombre de colonnes : 7

Colonnes :
['Customer_ID', 'Name', 'Age', 'Gender', 'Location', 'Join_Date', 'Total_Spent']

Types de données :
Customer_ID      int64
Name            object
Age              int64
Gender          object
Location        object
Join_Date       object
Total_Spent    float64
dtype: object

============================================================
PRODUCTS
============================================================
Nombre de lignes : 200
Nombre de colonnes : 5

Colonnes :
['Product_ID', 'Product_Name', 'Category', 'Price', 'Brand']

Types de données :
Product_ID        int64
Product_Name     object
Category         object
Price           float64
Brand            object
dtype: object

============================================================
SALES
============================================================
Nombre de lignes : 30000
Nombre de colonnes : 7

Colonnes :
['Sale_ID', 'Product_ID', 'Customer_ID', 'Date', 'Quantity', 'Sale_Price', 'Channel']

Types de données :
Sale_ID          int64
Product_ID       int64
Customer_ID      int64
Date            object
Quantity         int64
Sale_Price     float64
Channel         object
dtype: object

============================================================
MARKETING
============================================================
Nombre de lignes : 100
Nombre de colonnes : 8

Colonnes :
['Campaign_ID', 'Channel', 'Start_Date', 'End_Date', 'Budget', 'Impressions', 'Clicks', 'Conversions']

Types de données :
Campaign_ID      int64
Channel         object
Start_Date      object
End_Date        object
Budget         float64
Impressions      int64
Clicks           int64
Conversions      int64
dtype: object

In [20]:
print("Valeurs manquantes")

for nom, df in datasets.items():
    print("\n" + "=" * 60)
    print(nom)
    print("=" * 60)

    missing = df.isnull().sum()

    print(missing)

Valeurs manquantes

============================================================
CUSTOMERS
============================================================
Customer_ID    0
Name           0
Age            0
Gender         0
Location       0
Join_Date      0
Total_Spent    0
dtype: int64

============================================================
PRODUCTS
============================================================
Product_ID      0
Product_Name    0
Category        0
Price           0
Brand           0
dtype: int64

============================================================
SALES
============================================================
Sale_ID        0
Product_ID     0
Customer_ID    0
Date           0
Quantity       0
Sale_Price     0
Channel        0
dtype: int64

============================================================
MARKETING
============================================================
Campaign_ID    0
Channel        0
Start_Date     0
End_Date       0
Budget         0
Impressions    0
Clicks         0
Conversions    0
dtype: int64

In [21]:
for nom, df in datasets.items():
    print("\n" + "=" * 60)
    print(nom)
    print("=" * 60)

    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)

    result = pd.DataFrame({
        "Valeurs_manquantes": missing,
        "Pourcentage": missing_pct
    })

    display(result)

============================================================
CUSTOMERS
============================================================

             Valeurs_manquantes  Pourcentage
Customer_ID                   0          0.0
Name                          0          0.0
Age                           0          0.0
Gender                        0          0.0
Location                      0          0.0
Join_Date                     0          0.0
Total_Spent                   0          0.0

============================================================
PRODUCTS
============================================================

              Valeurs_manquantes  Pourcentage
Product_ID                     0          0.0
Product_Name                   0          0.0
Category                       0          0.0
Price                          0          0.0
Brand                          0          0.0

============================================================
SALES
============================================================

             Valeurs_manquantes  Pourcentage
Sale_ID                       0          0.0
Product_ID                    0          0.0
Customer_ID                   0          0.0
Date                          0          0.0
Quantity                      0          0.0
Sale_Price                    0          0.0
Channel                       0          0.0

============================================================
MARKETING
============================================================

             Valeurs_manquantes  Pourcentage
Campaign_ID                   0          0.0
Channel                       0          0.0
Start_Date                    0          0.0
End_Date                      0          0.0
Budget                        0          0.0
Impressions                   0          0.0
Clicks                        0          0.0
Conversions                   0          0.0

In [22]:
print("Doublons")

for nom, df in datasets.items():
    print(f"{nom} : {df.duplicated().sum()} doublon(s)")

Doublons
CUSTOMERS : 0 doublon(s)
PRODUCTS : 0 doublon(s)
SALES : 0 doublon(s)
MARKETING : 0 doublon(s)

In [23]:
print(" VALEURS UNIQUES DES VARIABLES CATÉGORIELLES ")

print("\n CUSTOMERS ")
print("Gender :", customers["Gender"].unique())
print("Nombre de Gender :", customers["Gender"].nunique())

print("\nLocation :")
print(customers["Location"].value_counts())

print("\n  PRODUCTS ")
print("Category :", products["Category"].unique())
print("Nombre de catégories :", products["Category"].nunique())

print("\nBrand :")
print(products["Brand"].value_counts())

print("\n SALES ")
print("Channel :", sales["Channel"].unique())
print("Nombre de channels :", sales["Channel"].nunique())

print("\n  MARKETING ")
print("Channel :", marketing["Channel"].unique())
print("Nombre de channels :", marketing["Channel"].nunique())

 VALEURS UNIQUES DES VARIABLES CATÉGORIELLES

 CUSTOMERS
Gender : ['Female' 'Male']
Nombre de Gender : 2

Location :
Location
New York       1769
Los Angeles    1580
Chicago        1398
Houston        1204
Phoenix        1049
Name: count, dtype: int64

  PRODUCTS
Category : ['Electronic Accessories' 'Lifestyle' 'Health & Beauty' 'Home'
 'Sports & Travel']
Nombre de catégories : 5

Brand :
Brand
Brand A    20
Brand B    20
Brand C    20
Brand D    20
Brand E    20
Brand F    20
Brand G    20
Brand H    20
Brand I    20
Brand J    20
Name: count, dtype: int64

 SALES
Channel : ['Online' 'In-Store']
Nombre de channels : 2

  MARKETING
Channel : ['Email' 'In-Store' 'Online' 'TV' 'Social']
Nombre de channels : 5

In [24]:
print("===== VÉRIFICATION DES IDENTIFIANTS =====")

print("\nCUSTOMER_ID")
print("Nombre de lignes :", len(customers))
print("Nombre de Customer_ID uniques :", customers["Customer_ID"].nunique())

print("\nPRODUCT_ID")
print("Nombre de lignes :", len(products))
print("Nombre de Product_ID uniques :", products["Product_ID"].nunique())

print("\nSALE_ID")
print("Nombre de lignes :", len(sales))
print("Nombre de Sale_ID uniques :", sales["Sale_ID"].nunique())

print("\nCAMPAIGN_ID")
print("Nombre de lignes :", len(marketing))
print("Nombre de Campaign_ID uniques :", marketing["Campaign_ID"].nunique())

===== VÉRIFICATION DES IDENTIFIANTS =====

CUSTOMER_ID
Nombre de lignes : 7000
Nombre de Customer_ID uniques : 7000

PRODUCT_ID
Nombre de lignes : 200
Nombre de Product_ID uniques : 200

SALE_ID
Nombre de lignes : 30000
Nombre de Sale_ID uniques : 30000

CAMPAIGN_ID
Nombre de lignes : 100
Nombre de Campaign_ID uniques : 100

In [25]:
print("===== INTÉGRITÉ RÉFÉRENTIELLE =====")

# Vérification des Customer_ID
customer_ids = set(customers["Customer_ID"])
sales_customer_ids = set(sales["Customer_ID"])

missing_customers = sales_customer_ids - customer_ids

print("\n--- CUSTOMER_ID ---")
print("Customer_ID utilisés dans Sales :", len(sales_customer_ids))
print("Customer_ID absents de Customers :", len(missing_customers))

if len(missing_customers) == 0:
    print("OK Tous les Customer_ID de Sales existent dans Customers.")
else:
    print("FAAHHHH Customer_ID manquants dans Customers :")
    print(missing_customers)


# Vérification des Product_ID
product_ids = set(products["Product_ID"])
sales_product_ids = set(sales["Product_ID"])

missing_products = sales_product_ids - product_ids

print("\n--- PRODUCT_ID ---")
print("Product_ID utilisés dans Sales :", len(sales_product_ids))
print("Product_ID absents de Products :", len(missing_products))

if len(missing_products) == 0:
    print("OK Tous les Product_ID de Sales existent dans Products.")
else:
    print(" FAAHHHH Product_ID manquants dans Products :")
    print(missing_products)

===== INTÉGRITÉ RÉFÉRENTIELLE =====

--- CUSTOMER_ID ---
Customer_ID utilisés dans Sales : 6325
Customer_ID absents de Customers : 0
OK Tous les Customer_ID de Sales existent dans Customers.

--- PRODUCT_ID ---
Product_ID utilisés dans Sales : 200
Product_ID absents de Products : 0
OK Tous les Product_ID de Sales existent dans Products.

In [26]:
print("===== INSPECTION DES DATES =====")

print("\n--- CUSTOMERS : Join_Date ---")
display(customers["Join_Date"].head(10))

print("\n--- SALES : Date ---")
display(sales["Date"].head(10))

print("\n--- MARKETING : Start_Date ---")
display(marketing["Start_Date"].head(10))

print("\n--- MARKETING : End_Date ---")
display(marketing["End_Date"].head(10))

===== INSPECTION DES DATES =====

--- CUSTOMERS : Join_Date ---

0    13 12 2021
1    08 03 2023
2    29 04 2021
3    04 06 2022
4    03 01 2023
5    21 03 2021
6    23 02 2022
7    07 08 2022
8    13 12 2022
9    22 08 2021
Name: Join_Date, dtype: object

--- SALES : Date ---

0    30 01 2024
1    12 04 2024
2    16 01 2024
3    10 02 2024
4    11 09 2024
5    31 07 2024
6    06 10 2024
7    22 08 2024
8    05 03 2024
9    21 12 2024
Name: Date, dtype: object

--- MARKETING : Start_Date ---

0    15 08 2024
1    09 10 2024
2    24 04 2024
3    17 10 2024
4    04 05 2024
5    05 10 2024
6    27 03 2024
7    29 01 2024
8    27 06 2024
9    01 06 2024
Name: Start_Date, dtype: object

--- MARKETING : End_Date ---

0    07 09 2024
1    19 10 2024
2    22 05 2024
3    29 10 2024
4    25 05 2024
5    13 10 2024
6    24 04 2024
7    23 02 2024
8    09 07 2024
9    12 06 2024
Name: End_Date, dtype: object

In [27]:
print("===== NOMBRE DE FORMATS / VALEURS UNIQUES =====")

print("Join_Date :", customers["Join_Date"].nunique())
print("Date :", sales["Date"].nunique())
print("Start_Date :", marketing["Start_Date"].nunique())
print("End_Date :", marketing["End_Date"].nunique())

===== NOMBRE DE FORMATS / VALEURS UNIQUES =====
Join_Date : 1091
Date : 366
Start_Date : 79
End_Date : 88

In [28]:
# ============================================================
# CONVERSION DES COLONNES DE DATES
# ============================================================

customers["Join_Date"] = pd.to_datetime(
    customers["Join_Date"],
    format="%d %m %Y",
    errors="coerce"
)

sales["Date"] = pd.to_datetime(
    sales["Date"],
    format="%d %m %Y",
    errors="coerce"
)

marketing["Start_Date"] = pd.to_datetime(
    marketing["Start_Date"],
    format="%d %m %Y",
    errors="coerce"
)

marketing["End_Date"] = pd.to_datetime(
    marketing["End_Date"],
    format="%d %m %Y",
    errors="coerce"
)

print("Conversion des dates terminée.")

Conversion des dates terminée.

In [29]:
# ============================================================
# VÉRIFICATION DES TYPES APRÈS CONVERSION
# ============================================================

print("===== TYPES APRÈS CONVERSION =====")

print("\nCUSTOMERS")
print(customers.dtypes)

print("\nSALES")
print(sales.dtypes)

print("\nMARKETING")
print(marketing.dtypes)

===== TYPES APRÈS CONVERSION =====

CUSTOMERS
Customer_ID             int64
Name                   object
Age                     int64
Gender                 object
Location               object
Join_Date      datetime64[ns]
Total_Spent           float64
dtype: object

SALES
Sale_ID                 int64
Product_ID              int64
Customer_ID             int64
Date           datetime64[ns]
Quantity                int64
Sale_Price            float64
Channel                object
dtype: object

MARKETING
Campaign_ID             int64
Channel                object
Start_Date     datetime64[ns]
End_Date       datetime64[ns]
Budget                float64
Impressions             int64
Clicks                  int64
Conversions             int64
dtype: object

In [30]:
# ============================================================
# VÉRIFICATION DES DATES INVALIDES
# ============================================================

print("===== DATES INVALIDES =====")

print("\nCustomers - Join_Date :", customers["Join_Date"].isna().sum())
print("Sales - Date :", sales["Date"].isna().sum())
print("Marketing - Start_Date :", marketing["Start_Date"].isna().sum())
print("Marketing - End_Date :", marketing["End_Date"].isna().sum())

===== DATES INVALIDES =====

Customers - Join_Date : 0
Sales - Date : 0
Marketing - Start_Date : 0
Marketing - End_Date : 0

In [31]:
print("===== COHÉRENCE DES DATES DES CAMPAGNES =====")

invalid_campaign_dates = marketing[
    marketing["Start_Date"] > marketing["End_Date"]
]

print("Nombre de campagnes avec des dates incohérentes :",
      len(invalid_campaign_dates))

if len(invalid_campaign_dates) == 0:
    print("✓ Toutes les campagnes ont des dates cohérentes.")
else:
    print("⚠ Campagnes incohérentes :")
    display(invalid_campaign_dates)

===== COHÉRENCE DES DATES DES CAMPAGNES =====
Nombre de campagnes avec des dates incohérentes : 0
✓ Toutes les campagnes ont des dates cohérentes.

In [32]:
print("===== STATISTIQUES DES VARIABLES NUMÉRIQUES =====")

print("\n--- CUSTOMERS ---")
display(customers[["Age", "Total_Spent"]].describe())

print("\n--- PRODUCTS ---")
display(products[["Price"]].describe())

print("\n--- SALES ---")
display(sales[["Quantity", "Sale_Price"]].describe())

print("\n--- MARKETING ---")
display(
    marketing[
        ["Budget", "Impressions", "Clicks", "Conversions"]
    ].describe()
)

===== STATISTIQUES DES VARIABLES NUMÉRIQUES =====

--- CUSTOMERS ---

               Age  Total_Spent
count  7000.000000  7000.000000
mean     35.518714   682.106243
std      10.457512   654.742978
min      18.000000     0.000000
25%      28.000000   189.385000
50%      35.000000   502.780000
75%      43.000000   978.990000
max      70.000000  5610.330000

--- PRODUCTS ---

            Price
count  200.000000
mean    87.774050
std     49.305039
min      8.480000
25%     44.660000
50%     80.875000
75%    126.335000
max    198.510000

--- SALES ---

           Quantity    Sale_Price
count  30000.000000  30000.000000
mean       1.932400     82.161757
std        1.121846     46.956487
min        1.000000      7.240000
25%        1.000000     41.357500
50%        2.000000     75.420000
75%        3.000000    116.972500
max        5.000000    207.760000

--- MARKETING ---

            Budget    Impressions        Clicks  Conversions
count   100.000000     100.000000    100.000000   100.000000
mean   2528.738700   73203.480000   3364.580000   299.070000
std    1266.012945   39839.704872   2406.309128   268.738702
min     408.470000   10987.000000    244.000000    13.000000
25%    1587.845000   40090.000000   1491.500000   122.250000
50%    2389.530000   71433.000000   2783.000000   223.500000
75%    3391.305000  106220.750000   4520.250000   393.750000
max    4920.660000  149125.000000  11361.000000  1365.000000

In [33]:
print("===== CONTRÔLES MÉTIER =====")

# ------------------------------------------------------------
# CUSTOMERS
# ------------------------------------------------------------

print("\n--- CUSTOMERS ---")

invalid_age = customers[
    (customers["Age"] <= 0) |
    (customers["Age"] > 100)
]

invalid_spent = customers[
    customers["Total_Spent"] < 0
]

print("Âges invalides :", len(invalid_age))
print("Total_Spent négatif :", len(invalid_spent))


# ------------------------------------------------------------
# PRODUCTS
# ------------------------------------------------------------

print("\n--- PRODUCTS ---")

invalid_price = products[
    products["Price"] <= 0
]

print("Prix invalides :", len(invalid_price))


# ------------------------------------------------------------
# SALES
# ------------------------------------------------------------

print("\n--- SALES ---")

invalid_quantity = sales[
    sales["Quantity"] <= 0
]

invalid_sale_price = sales[
    sales["Sale_Price"] <= 0
]

print("Quantités invalides :", len(invalid_quantity))
print("Sale_Price invalides :", len(invalid_sale_price))


# ------------------------------------------------------------
# MARKETING
# ------------------------------------------------------------

print("\n--- MARKETING ---")

invalid_budget = marketing[
    marketing["Budget"] <= 0
]

invalid_impressions = marketing[
    marketing["Impressions"] < 0
]

invalid_clicks = marketing[
    marketing["Clicks"] < 0
]

invalid_conversions = marketing[
    marketing["Conversions"] < 0
]

clicks_gt_impressions = marketing[
    marketing["Clicks"] > marketing["Impressions"]
]

conversions_gt_clicks = marketing[
    marketing["Conversions"] > marketing["Clicks"]
]

print("Budgets invalides :", len(invalid_budget))
print("Impressions négatives :", len(invalid_impressions))
print("Clicks négatifs :", len(invalid_clicks))
print("Conversions négatives :", len(invalid_conversions))
print("Clicks > Impressions :", len(clicks_gt_impressions))
print("Conversions > Clicks :", len(conversions_gt_clicks))

===== CONTRÔLES MÉTIER =====

--- CUSTOMERS ---
Âges invalides : 0
Total_Spent négatif : 0

--- PRODUCTS ---
Prix invalides : 0

--- SALES ---
Quantités invalides : 0
Sale_Price invalides : 0

--- MARKETING ---
Budgets invalides : 0
Impressions négatives : 0
Clicks négatifs : 0
Conversions négatives : 0
Clicks > Impressions : 0
Conversions > Clicks : 0

In [34]:
def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]

    return {
        "variable": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "borne_inférieure": lower_bound,
        "borne_supérieure": upper_bound,
        "nombre_outliers": len(outliers)
    }


outlier_results = []

for column in ["Age", "Total_Spent"]:
    outlier_results.append(
        detect_outliers_iqr(customers, column)
    )

outlier_results.append(
    detect_outliers_iqr(products, "Price")
)

for column in ["Quantity", "Sale_Price"]:
    outlier_results.append(
        detect_outliers_iqr(sales, column)
    )

for column in ["Budget", "Impressions", "Clicks", "Conversions"]:
    outlier_results.append(
        detect_outliers_iqr(marketing, column)
    )

outliers_df = pd.DataFrame(outlier_results)

display(outliers_df)

,variable,Q1,Q3,IQR,borne_inférieure,borne_supérieure,nombre_outliers
0,Age,28.0000,43.0000,15.000,5.5000,65.5000,19
1,Total_Spent,189.3850,978.9900,789.605,-995.0225,2163.3975,256
2,Price,44.6600,126.3350,81.675,-77.8525,248.8475,0
3,Quantity,1.0000,3.0000,2.000,-2.0000,6.0000,0
4,Sale_Price,41.3575,116.9725,75.615,-72.0650,230.3950,0
5,Budget,1587.8450,3391.3050,1803.460,-1117.3450,6096.4950,0
6,Impressions,40090.0000,106220.7500,66130.750,-59106.1250,205416.8750,0
7,Clicks,1491.5000,4520.2500,3028.750,-3051.6250,9063.3750,3
8,Conversions,122.2500,393.7500,271.500,-285.0000,801.0000,7

In [35]:
print("===== INSPECTION DES OUTLIERS =====")

# -------------------------
# Age
# -------------------------
print("\n--- OUTLIERS AGE ---")

Q1 = customers["Age"].quantile(0.25)
Q3 = customers["Age"].quantile(0.75)
IQR = Q3 - Q1

age_outliers = customers[
    (customers["Age"] < Q1 - 1.5 * IQR) |
    (customers["Age"] > Q3 + 1.5 * IQR)
]

display(
    age_outliers[
        ["Customer_ID", "Name", "Age", "Gender",
         "Location", "Join_Date", "Total_Spent"]
    ].sort_values("Age")
)


# -------------------------
# Total_Spent
# -------------------------
print("\n--- OUTLIERS TOTAL_SPENT ---")

Q1 = customers["Total_Spent"].quantile(0.25)
Q3 = customers["Total_Spent"].quantile(0.75)
IQR = Q3 - Q1

spent_outliers = customers[
    (customers["Total_Spent"] < Q1 - 1.5 * IQR) |
    (customers["Total_Spent"] > Q3 + 1.5 * IQR)
]

print("Nombre :", len(spent_outliers))

display(
    spent_outliers[
        ["Customer_ID", "Name", "Age",
         "Gender", "Location", "Total_Spent"]
    ].sort_values("Total_Spent", ascending=False).head(20)
)


# -------------------------
# Clicks
# -------------------------
print("\n--- OUTLIERS CLICKS ---")

Q1 = marketing["Clicks"].quantile(0.25)
Q3 = marketing["Clicks"].quantile(0.75)
IQR = Q3 - Q1

click_outliers = marketing[
    (marketing["Clicks"] < Q1 - 1.5 * IQR) |
    (marketing["Clicks"] > Q3 + 1.5 * IQR)
]

display(click_outliers)


# -------------------------
# Conversions
# -------------------------
print("\n--- OUTLIERS CONVERSIONS ---")

Q1 = marketing["Conversions"].quantile(0.25)
Q3 = marketing["Conversions"].quantile(0.75)
IQR = Q3 - Q1

conversion_outliers = marketing[
    (marketing["Conversions"] < Q1 - 1.5 * IQR) |
    (marketing["Conversions"] > Q3 + 1.5 * IQR)
]

display(conversion_outliers)

===== INSPECTION DES OUTLIERS =====

--- OUTLIERS AGE ---

,Customer_ID,Name,Age,Gender,Location,Join_Date,Total_Spent
1865,3866,Customer_3866,66,Male,Houston,2022-05-15,372.83
3935,5936,Customer_5936,66,Male,New York,2022-06-05,878.47
6579,8580,Customer_8580,67,Male,Houston,2023-03-22,226.77
1197,3198,Customer_3198,67,Male,Los Angeles,2023-04-03,67.14
4439,6440,Customer_6440,67,Female,Houston,2021-03-31,1260.33
1545,3546,Customer_3546,68,Female,Chicago,2023-10-05,438.53
5861,7862,Customer_7862,68,Female,Phoenix,2021-07-25,966.88
2121,4122,Customer_4122,68,Female,Los Angeles,2023-05-19,1636.16
6332,8333,Customer_8333,69,Male,Chicago,2021-08-22,534.77
2158,4159,Customer_4159,69,Female,Chicago,2021-03-01,554.42
6388,8389,Customer_8389,69,Female,Chicago,2023-06-18,334.54
4795,6796,Customer_6796,70,Female,Phoenix,2023-07-15,198.61
290,2291,Customer_2291,70,Female,Houston,2021-12-13,370.49
2898,4899,Customer_4899,70,Female,Houston,2022-09-08,0.00
2177,4178,Customer_4178,70,Male,Houston,2022-12-16,0.00
1660,3661,Customer_3661,70,Male,Los Angeles,2023-05-20,8.71
416,2417,Customer_2417,70,Female,Los Angeles,2023-02-18,297.37
3864,5865,Customer_5865,70,Female,New York,2021-07-01,161.76
2396,4397,Customer_4397,70,Female,New York,2023-06-24,115.40

--- OUTLIERS TOTAL_SPENT ---
Nombre : 256

      Customer_ID           Name  Age  Gender     Location  Total_Spent
4247         6248  Customer_6248   36  Female  Los Angeles      5610.33
3247         5248  Customer_5248   40  Female      Houston      5299.37
982          2983  Customer_2983   40  Female      Houston      4484.28
1947         3948  Customer_3948   29  Female      Phoenix      4437.17
4854         6855  Customer_6855   47    Male      Chicago      4270.52
1937         3938  Customer_3938   18    Male      Phoenix      4189.54
3217         5218  Customer_5218   31  Female  Los Angeles      4091.57
224          2225  Customer_2225   27  Female      Phoenix      3972.34
1552         3553  Customer_3553   49    Male      Chicago      3949.16
1382         3383  Customer_3383   50    Male      Chicago      3928.49
5067         7068  Customer_7068   52  Female      Phoenix      3897.78
1550         3551  Customer_3551   44    Male      Phoenix      3881.30
4739         6740  Customer_6740   41    Male  Los Angeles      3831.16
4607         6608  Customer_6608   36  Female     New York      3782.61
4878         6879  Customer_6879   24  Female      Chicago      3774.14
2061         4062  Customer_4062   24  Female      Phoenix      3751.21
1490         3491  Customer_3491   23  Female      Houston      3737.67
681          2682  Customer_2682   41  Female      Chicago      3665.35
6989         8990  Customer_8990   41  Female     New York      3612.48
545          2546  Customer_2546   49  Female     New York      3594.45

--- OUTLIERS CLICKS ---

,Campaign_ID,Channel,Start_Date,End_Date,Budget,Impressions,Clicks,Conversions
4,5,Online,2024-05-04,2024-05-25,2882.14,138243,10593,1365
52,53,In-Store,2024-04-20,2024-04-29,4218.23,128572,9780,1067
78,79,TV,2024-07-28,2024-08-25,972.58,145851,11361,1019

--- OUTLIERS CONVERSIONS ---

,Campaign_ID,Channel,Start_Date,End_Date,Budget,Impressions,Clicks,Conversions
4,5,Online,2024-05-04,2024-05-25,2882.14,138243,10593,1365
25,26,Email,2024-10-23,2024-11-04,1206.78,88611,6442,948
52,53,In-Store,2024-04-20,2024-04-29,4218.23,128572,9780,1067
68,69,In-Store,2024-07-24,2024-08-07,1834.43,107317,7690,1107
78,79,TV,2024-07-28,2024-08-25,972.58,145851,11361,1019
95,96,TV,2024-02-04,2024-02-11,4474.55,127578,6623,981
96,97,TV,2024-03-19,2024-04-16,4223.50,113461,7636,871

In [36]:
print("===== DECISION SUR LES OUTLIERS =====")

print("""
Aucune valeur aberrante n'a été supprimée.

- Age :
  Les valeurs entre 66 et 70 ans sont plausibles.
  => Conservation.

- Total_Spent :
  Les valeurs élevées correspondent potentiellement à des clients
  à forte valeur.
  => Conservation.

- Price :
  Aucun outlier détecté.
  => Conservation.

- Quantity :
  Aucun outlier détecté.
  => Conservation.

- Sale_Price :
  Aucun outlier détecté.
  => Conservation.

- Budget :
  Aucun outlier détecté.
  => Conservation.

- Impressions :
  Aucun outlier détecté.
  => Conservation.

- Clicks :
  3 valeurs statistiquement extrêmes mais cohérentes avec
  les impressions.
  => Conservation.

- Conversions :
  7 valeurs statistiquement extrêmes mais cohérentes avec
  les clicks.
  => Conservation.
""")

===== DECISION SUR LES OUTLIERS =====

Aucune valeur aberrante n'a été supprimée.

- Age :
  Les valeurs entre 66 et 70 ans sont plausibles.
  => Conservation.

- Total_Spent :
  Les valeurs élevées correspondent potentiellement à des clients
  à forte valeur.
  => Conservation.

- Price :
  Aucun outlier détecté.
  => Conservation.

- Quantity :
  Aucun outlier détecté.
  => Conservation.

- Sale_Price :
  Aucun outlier détecté.
  => Conservation.

- Budget :
  Aucun outlier détecté.
  => Conservation.

- Impressions :
  Aucun outlier détecté.
  => Conservation.

- Clicks :
  3 valeurs statistiquement extrêmes mais cohérentes avec
  les impressions.
  => Conservation.

- Conversions :
  7 valeurs statistiquement extrêmes mais cohérentes avec
  les clicks.
  => Conservation.

In [37]:
# ============================================================
# M2 - NETTOYAGE DU DATASET CUSTOMERS
# ============================================================

customers_clean = customers.copy()

print("===== AVANT NETTOYAGE =====")
print(customers_clean.info())

===== AVANT NETTOYAGE =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  7000 non-null   int64
 1   Name         7000 non-null   object
 2   Age          7000 non-null   int64
 3   Gender       7000 non-null   object
 4   Location     7000 non-null   object
 5   Join_Date    7000 non-null   datetime64[ns]
 6   Total_Spent  7000 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 382.9+ KB
None

In [38]:
# ============================================================
# 1. NORMALISATION DES NOMS DE COLONNES
# ============================================================

customers_clean.columns = (
    customers_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Colonnes après normalisation :")
print(customers_clean.columns.tolist())

Colonnes après normalisation :
['customer_id', 'name', 'age', 'gender', 'location', 'join_date', 'total_spent']

In [39]:
# ============================================================
# 2. NETTOYAGE DES VARIABLES TEXTUELLES
# ============================================================

text_columns = ["name", "gender", "location"]

for col in text_columns:
    customers_clean[col] = customers_clean[col].astype("string").str.strip()

print("Nettoyage des variables textuelles terminé.")

Nettoyage des variables textuelles terminé.

In [40]:
# ============================================================
# 3. CONTROLE DES VALEURS VIDES
# ============================================================

for col in text_columns:
    empty_count = (customers_clean[col] == "").sum()
    print(f"{col} : {empty_count} valeur(s) vide(s)")

name : 0 valeur(s) vide(s)
gender : 0 valeur(s) vide(s)
location : 0 valeur(s) vide(s)

In [41]:
# ============================================================
# 4. TYPES DEFINITIFS
# ============================================================

customers_clean["customer_id"] = customers_clean["customer_id"].astype("int64")
customers_clean["name"] = customers_clean["name"].astype("string")
customers_clean["age"] = customers_clean["age"].astype("int64")
customers_clean["gender"] = customers_clean["gender"].astype("string")
customers_clean["location"] = customers_clean["location"].astype("string")
customers_clean["join_date"] = pd.to_datetime(
    customers_clean["join_date"],
    errors="coerce"
)
customers_clean["total_spent"] = customers_clean["total_spent"].astype("float64")

In [42]:
# ============================================================
# 5. CONTROLE QUALITE FINAL
# ============================================================

print("===== CONTROLE FINAL CUSTOMERS =====")

print("\nDimensions :", customers_clean.shape)

print("\nValeurs manquantes :")
print(customers_clean.isnull().sum())

print("\nDoublons complets :", customers_clean.duplicated().sum())

print("\nCustomer_ID uniques :",
      customers_clean["customer_id"].nunique(),
      "/",
      len(customers_clean))

print("\nTypes :")
print(customers_clean.dtypes)

print("\nValeurs Gender :")
print(customers_clean["gender"].unique())

print("\nValeurs Location :")
print(customers_clean["location"].unique())

===== CONTROLE FINAL CUSTOMERS =====

Dimensions : (7000, 7)

Valeurs manquantes :
customer_id    0
name           0
age            0
gender         0
location       0
join_date      0
total_spent    0
dtype: int64

Doublons complets : 0

Customer_ID uniques : 7000 / 7000

Types :
customer_id             int64
name           string[python]
age                     int64
gender         string[python]
location       string[python]
join_date      datetime64[ns]
total_spent           float64
dtype: object

Valeurs Gender :
<StringArray>
['Female', 'Male']
Length: 2, dtype: string

Valeurs Location :
<StringArray>
['New York', 'Houston', 'Los Angeles', 'Chicago', 'Phoenix']
Length: 5, dtype: string

In [43]:
# ============================================================
# M2 - NETTOYAGE DU DATASET PRODUCTS
# ============================================================

products_clean = products.copy()

print("===== AVANT NETTOYAGE =====")
print(products_clean.info())

===== AVANT NETTOYAGE =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    200 non-null    int64
 1   Product_Name  200 non-null    object
 2   Category      200 non-null    object
 3   Price         200 non-null    float64
 4   Brand         200 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 7.9+ KB
None

In [44]:
# ============================================================
# 1. NORMALISATION DES NOMS DE COLONNES
# ============================================================

products_clean.columns = (
    products_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Colonnes après normalisation :")
print(products_clean.columns.tolist())

Colonnes après normalisation :
['product_id', 'product_name', 'category', 'price', 'brand']

In [45]:
# ============================================================
# 2. NETTOYAGE DES VARIABLES TEXTUELLES
# ============================================================

text_columns = ["product_name", "category", "brand"]

for col in text_columns:
    products_clean[col] = products_clean[col].astype("string").str.strip()

print("Nettoyage des variables textuelles terminé.")

Nettoyage des variables textuelles terminé.

In [46]:
# ============================================================
# 3. CONTROLE DES VALEURS VIDES
# ============================================================

for col in text_columns:
    empty_count = (products_clean[col] == "").sum()
    print(f"{col} : {empty_count} valeur(s) vide(s)")

product_name : 0 valeur(s) vide(s)
category : 0 valeur(s) vide(s)
brand : 0 valeur(s) vide(s)

In [47]:
# ============================================================
# 4. TYPES DEFINITIFS
# ============================================================

products_clean["product_id"] = products_clean["product_id"].astype("int64")
products_clean["product_name"] = products_clean["product_name"].astype("string")
products_clean["category"] = products_clean["category"].astype("string")
products_clean["price"] = products_clean["price"].astype("float64")
products_clean["brand"] = products_clean["brand"].astype("string")

In [48]:
# ============================================================
# 5. CONTROLE QUALITE FINAL
# ============================================================

print("===== CONTROLE FINAL PRODUCTS =====")

print("\nDimensions :", products_clean.shape)

print("\nValeurs manquantes :")
print(products_clean.isnull().sum())

print("\nDoublons complets :", products_clean.duplicated().sum())

print(
    "\nProduct_ID uniques :",
    products_clean["product_id"].nunique(),
    "/",
    len(products_clean)
)

print("\nTypes :")
print(products_clean.dtypes)

print("\nCatégories :")
print(products_clean["category"].unique())

print("\nMarques :")
print(products_clean["brand"].unique())

print("\nPrix min :", products_clean["price"].min())
print("Prix max :", products_clean["price"].max())

===== CONTROLE FINAL PRODUCTS =====

Dimensions : (200, 5)

Valeurs manquantes :
product_id      0
product_name    0
category        0
price           0
brand           0
dtype: int64

Doublons complets : 0

Product_ID uniques : 200 / 200

Types :
product_id               int64
product_name    string[python]
category        string[python]
price                  float64
brand           string[python]
dtype: object

Catégories :
<StringArray>
['Electronic Accessories',              'Lifestyle',        'Health & Beauty',
                   'Home',        'Sports & Travel']
Length: 5, dtype: string

Marques :
<StringArray>
['Brand A', 'Brand B', 'Brand C', 'Brand D', 'Brand E', 'Brand F', 'Brand G',
 'Brand H', 'Brand I', 'Brand J']
Length: 10, dtype: string

Prix min : 8.48
Prix max : 198.51

In [49]:
# ============================================================
# M2 - NETTOYAGE DU DATASET SALES
# ============================================================

sales_clean = sales.copy()

print("===== AVANT NETTOYAGE =====")
print(sales_clean.info())

===== AVANT NETTOYAGE =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sale_ID      30000 non-null  int64
 1   Product_ID   30000 non-null  int64
 2   Customer_ID  30000 non-null  int64
 3   Date         30000 non-null  datetime64[ns]
 4   Quantity     30000 non-null  int64
 5   Sale_Price   30000 non-null  float64
 6   Channel      30000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 1.6+ MB
None

In [50]:
# ============================================================
# 1. NORMALISATION DES NOMS DE COLONNES
# ============================================================

sales_clean.columns = (
    sales_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Colonnes après normalisation :")
print(sales_clean.columns.tolist())

Colonnes après normalisation :
['sale_id', 'product_id', 'customer_id', 'date', 'quantity', 'sale_price', 'channel']

In [51]:
# ============================================================
# 2. NETTOYAGE DES VARIABLES TEXTUELLES
# ============================================================

sales_clean["channel"] = (
    sales_clean["channel"]
    .astype("string")
    .str.strip()
)

print("Valeurs Channel :")
print(sales_clean["channel"].unique())

Valeurs Channel :
<StringArray>
['Online', 'In-Store']
Length: 2, dtype: string

In [52]:
# ============================================================
# 3. TYPES DEFINITIFS
# ============================================================

sales_clean["sale_id"] = sales_clean["sale_id"].astype("int64")
sales_clean["product_id"] = sales_clean["product_id"].astype("int64")
sales_clean["customer_id"] = sales_clean["customer_id"].astype("int64")

sales_clean["date"] = pd.to_datetime(
    sales_clean["date"],
    errors="coerce"
)

sales_clean["quantity"] = sales_clean["quantity"].astype("int64")
sales_clean["sale_price"] = sales_clean["sale_price"].astype("float64")
sales_clean["channel"] = sales_clean["channel"].astype("string")

In [53]:
# ============================================================
# 4. CONTROLE QUALITE FINAL SALES
# ============================================================

print("===== CONTROLE FINAL SALES =====")

print("\nDimensions :", sales_clean.shape)

print("\nValeurs manquantes :")
print(sales_clean.isnull().sum())

print("\nDoublons complets :", sales_clean.duplicated().sum())

print(
    "\nSale_ID uniques :",
    sales_clean["sale_id"].nunique(),
    "/",
    len(sales_clean)
)

print("\nProduct_ID uniques utilisés :",
      sales_clean["product_id"].nunique())

print("Customer_ID uniques utilisés :",
      sales_clean["customer_id"].nunique())

print("\nTypes :")
print(sales_clean.dtypes)

print("\nChannels :")
print(sales_clean["channel"].unique())

print("\nQuantité min :", sales_clean["quantity"].min())
print("Quantité max :", sales_clean["quantity"].max())

print("\nPrix de vente min :", sales_clean["sale_price"].min())
print("Prix de vente max :", sales_clean["sale_price"].max())

print("\nDate min :", sales_clean["date"].min())
print("Date max :", sales_clean["date"].max())

===== CONTROLE FINAL SALES =====

Dimensions : (30000, 7)

Valeurs manquantes :
sale_id        0
product_id     0
customer_id    0
date           0
quantity       0
sale_price     0
channel        0
dtype: int64

Doublons complets : 0

Sale_ID uniques : 30000 / 30000

Product_ID uniques utilisés : 200
Customer_ID uniques utilisés : 6325

Types :
sale_id                 int64
product_id              int64
customer_id             int64
date           datetime64[ns]
quantity                int64
sale_price            float64
channel        string[python]
dtype: object

Channels :
<StringArray>
['Online', 'In-Store']
Length: 2, dtype: string

Quantité min : 1
Quantité max : 5

Prix de vente min : 7.24
Prix de vente max : 207.76

Date min : 2024-01-01 00:00:00
Date max : 2024-12-31 00:00:00

In [54]:
# ============================================================
# 5. INTEGRITE REFERENTIELLE
# ============================================================

invalid_products = ~sales_clean["product_id"].isin(
    products_clean["product_id"]
)

invalid_customers = ~sales_clean["customer_id"].isin(
    customers_clean["customer_id"]
)

print("Product_ID inexistants :", invalid_products.sum())
print("Customer_ID inexistants :", invalid_customers.sum())

Product_ID inexistants : 0
Customer_ID inexistants : 0

In [55]:
# ============================================================
# 6. CONTROLES METIER
# ============================================================

print("===== CONTROLES METIER SALES =====")

print(
    "Quantités <= 0 :",
    (sales_clean["quantity"] <= 0).sum()
)

print(
    "Prix de vente <= 0 :",
    (sales_clean["sale_price"] <= 0).sum()
)

print(
    "Dates invalides :",
    sales_clean["date"].isna().sum()
)

===== CONTROLES METIER SALES =====
Quantités <= 0 : 0
Prix de vente <= 0 : 0
Dates invalides : 0

In [56]:
# ============================================================
# M2 - NETTOYAGE DU DATASET MARKETING
# ============================================================

marketing_clean = marketing.copy()

print("===== AVANT NETTOYAGE =====")
print(marketing_clean.info())

===== AVANT NETTOYAGE =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Campaign_ID  100 non-null    int64
 1   Channel      100 non-null    object
 2   Start_Date   100 non-null    datetime64[ns]
 3   End_Date     100 non-null    datetime64[ns]
 4   Budget       100 non-null    float64
 5   Impressions  100 non-null    int64
 6   Clicks       100 non-null    int64
 7   Conversions  100 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(1)
memory usage: 6.4+ KB
None

In [57]:
# ============================================================
# 1. NORMALISATION DES NOMS DE COLONNES
# ============================================================

marketing_clean.columns = (
    marketing_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Colonnes après normalisation :")
print(marketing_clean.columns.tolist())

Colonnes après normalisation :
['campaign_id', 'channel', 'start_date', 'end_date', 'budget', 'impressions', 'clicks', 'conversions']

In [58]:
# ============================================================
# 2. NETTOYAGE DES VARIABLES TEXTUELLES
# ============================================================

marketing_clean["channel"] = (
    marketing_clean["channel"]
    .astype("string")
    .str.strip()
)

print("Canaux marketing :")
print(marketing_clean["channel"].unique())

Canaux marketing :
<StringArray>
['Email', 'In-Store', 'Online', 'TV', 'Social']
Length: 5, dtype: string

In [59]:
# ============================================================
# 3. TYPES DEFINITIFS
# ============================================================

marketing_clean["campaign_id"] = marketing_clean["campaign_id"].astype("int64")

marketing_clean["start_date"] = pd.to_datetime(
    marketing_clean["start_date"],
    errors="coerce"
)

marketing_clean["end_date"] = pd.to_datetime(
    marketing_clean["end_date"],
    errors="coerce"
)

marketing_clean["budget"] = marketing_clean["budget"].astype("float64")
marketing_clean["impressions"] = marketing_clean["impressions"].astype("int64")
marketing_clean["clicks"] = marketing_clean["clicks"].astype("int64")
marketing_clean["conversions"] = marketing_clean["conversions"].astype("int64")

In [60]:
# ============================================================
# 4. CONTROLE QUALITE FINAL MARKETING
# ============================================================

print("===== CONTROLE FINAL MARKETING =====")

print("\nDimensions :", marketing_clean.shape)

print("\nValeurs manquantes :")
print(marketing_clean.isnull().sum())

print("\nDoublons complets :", marketing_clean.duplicated().sum())

print(
    "\nCampaign_ID uniques :",
    marketing_clean["campaign_id"].nunique(),
    "/",
    len(marketing_clean)
)

print("\nTypes :")
print(marketing_clean.dtypes)

print("\nChannels :")
print(marketing_clean["channel"].unique())

print("\nBudget min :", marketing_clean["budget"].min())
print("Budget max :", marketing_clean["budget"].max())

print("\nImpressions min :", marketing_clean["impressions"].min())
print("Impressions max :", marketing_clean["impressions"].max())

print("\nClicks min :", marketing_clean["clicks"].min())
print("Clicks max :", marketing_clean["clicks"].max())

print("\nConversions min :", marketing_clean["conversions"].min())
print("Conversions max :", marketing_clean["conversions"].max())

print("\nDate début min :", marketing_clean["start_date"].min())
print("Date début max :", marketing_clean["start_date"].max())

print("\nDate fin min :", marketing_clean["end_date"].min())
print("Date fin max :", marketing_clean["end_date"].max())

===== CONTROLE FINAL MARKETING =====

Dimensions : (100, 8)

Valeurs manquantes :
campaign_id    0
channel        0
start_date     0
end_date       0
budget         0
impressions    0
clicks         0
conversions    0
dtype: int64

Doublons complets : 0

Campaign_ID uniques : 100 / 100

Types :
campaign_id             int64
channel        string[python]
start_date     datetime64[ns]
end_date       datetime64[ns]
budget                float64
impressions             int64
clicks                  int64
conversions             int64
dtype: object

Channels :
<StringArray>
['Email', 'In-Store', 'Online', 'TV', 'Social']
Length: 5, dtype: string

Budget min : 408.47
Budget max : 4920.66

Impressions min : 10987
Impressions max : 149125

Clicks min : 244
Clicks max : 11361

Conversions min : 13
Conversions max : 1365

Date début min : 2024-01-01 00:00:00
Date début max : 2024-10-30 00:00:00

Date fin min : 2024-01-11 00:00:00
Date fin max : 2024-11-17 00:00:00

In [61]:
# ============================================================
# 5. CONTROLES METIER MARKETING
# ============================================================

print("===== CONTROLES METIER MARKETING =====")

print(
    "Budget <= 0 :",
    (marketing_clean["budget"] <= 0).sum()
)

print(
    "Impressions < 0 :",
    (marketing_clean["impressions"] < 0).sum()
)

print(
    "Clicks < 0 :",
    (marketing_clean["clicks"] < 0).sum()
)

print(
    "Conversions < 0 :",
    (marketing_clean["conversions"] < 0).sum()
)

print(
    "Clicks > Impressions :",
    (marketing_clean["clicks"] > marketing_clean["impressions"]).sum()
)

print(
    "Conversions > Clicks :",
    (marketing_clean["conversions"] > marketing_clean["clicks"]).sum()
)

print(
    "Start_Date > End_Date :",
    (marketing_clean["start_date"] > marketing_clean["end_date"]).sum()
)

print(
    "Dates invalides :",
    (
        marketing_clean["start_date"].isna() |
        marketing_clean["end_date"].isna()
    ).sum()
)

===== CONTROLES METIER MARKETING =====
Budget <= 0 : 0
Impressions < 0 : 0
Clicks < 0 : 0
Conversions < 0 : 0
Clicks > Impressions : 0
Conversions > Clicks : 0
Start_Date > End_Date : 0
Dates invalides : 0

In [62]:
# ============================================================
# M2 - VALIDATION GLOBALE DES DATASETS NETTOYES
# ============================================================

datasets_clean = {
    "customers": customers_clean,
    "products": products_clean,
    "sales": sales_clean,
    "marketing": marketing_clean
}

print("=" * 70)
print("VALIDATION GLOBALE DES DATASETS")
print("=" * 70)

for name, df in datasets_clean.items():

    print(f"\n===== {name.upper()} =====")

    print("Dimensions :", df.shape)
    print("Valeurs manquantes :", df.isnull().sum().sum())
    print("Doublons :", df.duplicated().sum())

    print("\nTypes :")
    print(df.dtypes)

======================================================================
VALIDATION GLOBALE DES DATASETS
======================================================================

===== CUSTOMERS =====
Dimensions : (7000, 7)
Valeurs manquantes : 0
Doublons : 0

Types :
customer_id             int64
name           string[python]
age                     int64
gender         string[python]
location       string[python]
join_date      datetime64[ns]
total_spent           float64
dtype: object

===== PRODUCTS =====
Dimensions : (200, 5)
Valeurs manquantes : 0
Doublons : 0

Types :
product_id               int64
product_name    string[python]
category        string[python]
price                  float64
brand           string[python]
dtype: object

===== SALES =====
Dimensions : (30000, 7)
Valeurs manquantes : 0
Doublons : 0

Types :
sale_id                 int64
product_id              int64
customer_id             int64
date           datetime64[ns]
quantity                int64
sale_price            float64
channel        string[python]
dtype: object

===== MARKETING =====
Dimensions : (100, 8)
Valeurs manquantes : 0
Doublons : 0

Types :
campaign_id             int64
channel        string[python]
start_date     datetime64[ns]
end_date       datetime64[ns]
budget                float64
impressions             int64
clicks                  int64
conversions             int64
dtype: object

In [63]:
# ============================================================
# CONTROLES DES IDENTIFIANTS
# ============================================================

print("=" * 70)
print("CONTROLE DES IDENTIFIANTS")
print("=" * 70)

print(
    "Customers :",
    customers_clean["customer_id"].nunique(),
    "/",
    len(customers_clean)
)

print(
    "Products :",
    products_clean["product_id"].nunique(),
    "/",
    len(products_clean)
)

print(
    "Sales :",
    sales_clean["sale_id"].nunique(),
    "/",
    len(sales_clean)
)

print(
    "Marketing :",
    marketing_clean["campaign_id"].nunique(),
    "/",
    len(marketing_clean)
)

======================================================================
CONTROLE DES IDENTIFIANTS
======================================================================
Customers : 7000 / 7000
Products : 200 / 200
Sales : 30000 / 30000
Marketing : 100 / 100

In [64]:
# ============================================================
# INTEGRITE REFERENTIELLE GLOBALE
# ============================================================

invalid_customer_ids = ~sales_clean["customer_id"].isin(
    customers_clean["customer_id"]
)

invalid_product_ids = ~sales_clean["product_id"].isin(
    products_clean["product_id"]
)

print("=" * 70)
print("INTEGRITE REFERENTIELLE")
print("=" * 70)

print(
    "Customer_ID invalides dans Sales :",
    invalid_customer_ids.sum()
)

print(
    "Product_ID invalides dans Sales :",
    invalid_product_ids.sum()
)

======================================================================
INTEGRITE REFERENTIELLE
======================================================================
Customer_ID invalides dans Sales : 0
Product_ID invalides dans Sales : 0

In [65]:
# ============================================================
# M2 - SAUVEGARDE DES DATASETS NETTOYES
# ============================================================

import os

# Création du dossier processed s'il n'existe pas
os.makedirs("data/processed", exist_ok=True)

# Sauvegarde des datasets
customers_clean.to_csv(
    "data/processed/customers_clean.csv",
    index=False
)

products_clean.to_csv(
    "data/processed/products_clean.csv",
    index=False
)

sales_clean.to_csv(
    "data/processed/sales_clean.csv",
    index=False
)

marketing_clean.to_csv(
    "data/processed/marketing_clean.csv",
    index=False
)

print("===== SAUVEGARDE TERMINEE =====")
print("customers_clean.csv      ✓")
print("products_clean.csv       ✓")
print("sales_clean.csv          ✓")
print("marketing_clean.csv      ✓")

===== SAUVEGARDE TERMINEE =====
customers_clean.csv      ✓
products_clean.csv       ✓
sales_clean.csv          ✓
marketing_clean.csv      ✓

In [66]:
# ============================================================
# VERIFICATION DES FICHIERS
# ============================================================

print("===== FICHIERS DANS data/processed =====")

!ls -lh data/processed

===== FICHIERS DANS data/processed =====

'ls' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

In [67]:
# ============================================================
# RELECTURE DES FICHIERS NETTOYES
# ============================================================

customers_check = pd.read_csv(
    "data/processed/customers_clean.csv"
)

products_check = pd.read_csv(
    "data/processed/products_clean.csv"
)

sales_check = pd.read_csv(
    "data/processed/sales_clean.csv"
)

marketing_check = pd.read_csv(
    "data/processed/marketing_clean.csv"
)

print("===== CONTROLE APRES SAUVEGARDE =====")

print("Customers :", customers_check.shape)
print("Products  :", products_check.shape)
print("Sales     :", sales_check.shape)
print("Marketing :", marketing_check.shape)

===== CONTROLE APRES SAUVEGARDE =====
Customers : (7000, 7)
Products  : (200, 5)
Sales     : (30000, 7)
Marketing : (100, 8)